// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: grpc-b/grpc-b.proto

package grpc_b

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type WorldRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldRequest) Reset() {
	*x = WorldRequest{}
	mi := &file_grpc_b_grpc_b_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldRequest) ProtoMessage() {}

func (x *WorldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_b_grpc_b_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldRequest.ProtoReflect.Descriptor instead.
func (*WorldRequest) Descriptor() ([]byte, []int) {
	return file_grpc_b_grpc_b_proto_rawDescGZIP(), []int{0}
}

func (x *WorldRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The response message containing the greetings
type WorldReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldReply) Reset() {
	*x = WorldReply{}
	mi := &file_grpc_b_grpc_b_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldReply) ProtoMessage() {}

func (x *WorldReply) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_b_grpc_b_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldReply.ProtoReflect.Descriptor instead.
func (*WorldReply) Descriptor() ([]byte, []int) {
	return file_grpc_b_grpc_b_proto_rawDescGZIP(), []int{1}
}

func (x *WorldReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_grpc_b_grpc_b_proto protoreflect.FileDescriptor

const file_grpc_b_grpc_b_proto_rawDesc = "" +
	"\n" +
	"\x13grpc-b/grpc-b.proto\x12\x06grpc_b\"\"\n" +
	"\fWorldRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"&\n" +
	"\n" +
	"WorldReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2A\n" +
	"\aGreeter\x126\n" +
	"\bSayWorld\x12\x14.grpc_b.WorldRequest\x1a\x12.grpc_b.WorldReply\"\x00B:Z8github.com/ashleyconnor/slog-test/cmd/grpc/grpc-b/grpc-bb\x06proto3"

var (
	file_grpc_b_grpc_b_proto_rawDescOnce sync.Once
	file_grpc_b_grpc_b_proto_rawDescData []byte
)

func file_grpc_b_grpc_b_proto_rawDescGZIP() []byte {
	file_grpc_b_grpc_b_proto_rawDescOnce.Do(func() {
		file_grpc_b_grpc_b_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_b_grpc_b_proto_rawDesc), len(file_grpc_b_grpc_b_proto_rawDesc)))
	})
	return file_grpc_b_grpc_b_proto_rawDescData
}

var file_grpc_b_grpc_b_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpc_b_grpc_b_proto_goTypes = []any{
	(*WorldRequest)(nil), // 0: grpc_b.WorldRequest
	(*WorldReply)(nil),   // 1: grpc_b.WorldReply
}
var file_grpc_b_grpc_b_proto_depIdxs = []int32{
	0, // 0: grpc_b.Greeter.SayWorld:input_type -> grpc_b.WorldRequest
	1, // 1: grpc_b.Greeter.SayWorld:output_type -> grpc_b.WorldReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_b_grpc_b_proto_init() }
func file_grpc_b_grpc_b_proto_init() {
	if File_grpc_b_grpc_b_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_b_grpc_b_proto_rawDesc), len(file_grpc_b_grpc_b_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_b_grpc_b_proto_goTypes,
		DependencyIndexes: file_grpc_b_grpc_b_proto_depIdxs,
		MessageInfos:      file_grpc_b_grpc_b_proto_msgTypes,
	}.Build()
	File_grpc_b_grpc_b_proto = out.File
	file_grpc_b_grpc_b_proto_goTypes = nil
	file_grpc_b_grpc_b_proto_depIdxs = nil
}
